-- Create the private 'documents' bucket for uploaded print files.
-- All customer uploads go through signed URLs generated by the
-- service-role key; direct anon/public access is blocked.

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false);

-- Storage policies: only the service role can read/write.
-- The service-role key bypasses these, but they deny any
-- attempt from the anon key or authenticated users directly.

create policy "Service role only: insert"
  on storage.objects for insert
  to authenticated, anon
  with check (false);

create policy "Service role only: select"
  on storage.objects for select
  to authenticated, anon
  using (false);

create policy "Service role only: update"
  on storage.objects for update
  to authenticated, anon
  using (false);

create policy "Service role only: delete"
  on storage.objects for delete
  to authenticated, anon
  using (false);
